FROM python:3.10-slim

WORKDIR /app
ENV PYTHONPATH=/app

COPY requirements-bridge.txt .
RUN pip install --no-cache-dir -r requirements-bridge.txt

COPY someip_network/ ./someip_network/
COPY attacks/        ./attacks/

CMD ["python", "-m", "someip_network.bridge"]
